name: pylint static check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install pylint
      run: |
        pip install pylint
    - name: Run all static checks on .py files in mayan/apps
      run: pylint --exit-zero mayan/apps
