name: Wily
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install wily
      run: |
       python -m pip install --upgrade pip
       python -m pip install wily
    - name: Build wily
      run: wily build mayan/apps/documents/views/
    - name: Run wily rank
      run: wily rank 
