name: Wily
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install wily
      run: pip install wily
    - name: Make new branch for wily
      run: git checkout -b branch_for_wily
    - name: Build wily
      run: wily build .
    - name: Run wily rank
      run: wily rank 
