name: Wily
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: ls
    - name: Install wily
      run: pip install wily
    - name: Build wily mayan/
      run: wily build 
    - name: Run wily rank
      run: wily rank 
